### ISSUE TITLE
NullPointer when setting Wall Banner facing

### ISSUE THREAD

**Issue by toddharrison** [CanaryModTeam/CanaryLib#101]
`BannerProperties.applyFacing(block, BlockFace.WEST);` gives the following:

    Caused by: java.lang.NullPointerException: 'BlockProperty property' cannot be null
	    at net.visualillusionsent.utils.Verify.notNull(Verify.java:87) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	    at net.canarymod.api.world.blocks.properties.helpers.BlockProperties.apply(BlockProperties.java:22) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
	    at net.canarymod.api.world.blocks.properties.helpers.BannerProperties.applyFacing(BannerProperties.java:43) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]

**Comment by darkdiplomat** [comment]
Well this is gonna require me to rethink the system...

**Comment by darkdiplomat** [comment]
https://github.com/CanaryModTeam/CanaryLib/commit/f4b7e454bd9f826da74a2962a50bd1e726c72f9f
