### ISSUE TITLE
IllegalArgumentException when setting Acacia or Dark Oak Variants

### ISSUE THREAD

**Issue by toddharrison** [CanaryModTeam/CanaryLib#99]
I'm getting an IllegalArgumentException when I try to set Acacia or Dark Oak as a variant on Log2. The property I'm using is: `WoodProperties.Variant.DARK_OAK` with command `LogProperties.applyVariant(block, variant);`

Stack trace:

    Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[oak, spruce, birch, jungle]} to dark_oak on block minecraft:log2, it is not an allowed value
        at net.minecraft.block.state.BlockState$StateImplemenation.a(BlockState.java:144) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.api.world.blocks.CanaryBlock.setPropertyValue(CanaryBlock.java:402) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.api.world.blocks.properties.helpers.BlockProperties.apply(BlockProperties.java:24) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]
        at net.canarymod.api.world.blocks.properties.helpers.LogProperties.applyVariant(LogProperties.java:98) ~[CanaryMod-1.8.0-1.2.0-SNAPSHOT-shaded.jar:1.8.0-1.2.0-SNAPSHOT]

**Comment by toddharrison** [comment]
Hoppers? Who said anything about hoppers? Can has logz2 pleaz? ;)
